apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMapName }}
  namespace: {{ .Values.namespace }}
data:
  APP_MODE: {{ .Values.config.appMode | quote }}
  APP_COLOR: {{ .Values.config.appColor | quote }}
